### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/julia#320]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/julia/issues/311)
- [x] [Add key features](https://github.com/exercism/julia/issues/312)
- [x] [Add tags](https://github.com/exercism/julia/issues/313)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/julia/issues/314)
- [ ] [Update status of track](https://github.com/exercism/julia/issues/318)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/julia/issues/319)
- [ ] [Pass linting checks](https://github.com/exercism/julia/issues/315)
- [ ] [Build Test Runner](https://github.com/exercism/julia/issues/316)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/julia/issues/317) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/julia/issues/334)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by colinleach** [comment]
Anything that still hasn't been done 4+ years later is probably not relevant.
